services:
  release-downloader:
    image: ghcr.io/nervebing/release-downloader:latest
    container_name: release-downloader
    restart: always
    environment:
      RD_REPOSITORY: fastfetch-cli/fastfetch
#      RD_TAG: 2.11.*
#      RD_FILENAME: .*linux.*amd64.*.
#      RD_LATEST: true
#      RD_PRERELEASE: true
#      RD_TOKEN: ${GITHUB_TOKEN}
#      RD_PATH: /mnt/release-downloader
#      RD_INTERVAL: 24h
#      RD_NOW: true
#      RD_TIMEOUT: 1m
#      RD_ASSET_TAG: true
#      RD_ASSET_DATE: true
    volumes:
      - ./data:/mnt/release-downloader
