services:
  release-downloader:
    image: ghcr.io/nervebing/release-downloader:latest
    container_name: release-downloader
    restart: always
#    user: 1000:1000
    environment:
      REPOSITORY: fastfetch-cli/fastfetch # github repository, {owner}/{repo}
      TAG: 2.11.* # optional, default: '', download assets from a specific tag (eg: regexp '.*.18.*')
      FILENAME: .*linux.*amd64.*. # optional, default: '', download assets from a specific filename, excluding tarball or zipball (eg: regexp '.*linux-arm64.*.gz')
      LATEST: true # optional, default: false, download target as latest release
      PRERELEASE: true # optional, default: false, download target as prerelease
      TOKEN: ${GITHUB_TOKEN} # optional, default: '', github personal access token
      PATH: /mnt/release-downloader # optional, default: './tmp', download path
      INTERVAL: 24h # optional, default: 1h, download task interval
      NOW: # optional, default: false, immediately run
    volumes:
      - ./data:/mnt/release-downloader
